# This file defines parameters specific to the Maelstrom ROV
#
# When looking at the ROV from above, the thruster placement is:
#  ___    ___
# |   |__|   |
# |F1      F2|    N
# |    F5    |    ^
# |          | W<-|->E
# |    F6    |    v
# |F4      F3|    S
# |__________|
#   REAR END
#
# Using the compass shown:
# F1 is positive NE
# F2 is positive NW
# F3 is positive SW
# F4 is positive SE
# F5 is positive down
# F6 is positive down

num_control_dof: 5
num_thrusters: 6
thrust_configuration:
 [[    0.0,  0.7071, -0.7071,    0.0,  0.7071, -0.7071], # Surge
  [    0.0, -0.7071, -0.7071,    0.0,  0.7071,  0.7071], # Sway
  [    1.0,     0.0,     0.0,    1.0,     0.0,     0.0], # Heave
  [-0.1600, -0.0467,  0.0467, 0.1600, -0.0467,  0.0467], # Pitch
  [    0.0, -0.2143,  0.2143,    0.0,  0.2143, -0.2143]] # Yaw
