# This file defines parameters specific to the Maelstrom ROV
#
# When looking at the ROV from above, the thruster placement is:
#  ___    ___
# |   |__|   |
# |F1      F2|    N
# |    F5    |    ^
# |          | W<-|->E
# |    F6    |    v
# |F4      F3|    S
# |__________|
#   REAR END
#
# Using the compass shown:
# F1 is positive NE
# F2 is positive NW
# F3 is positive SW
# F4 is positive SE
# F5 is positive down
# F6 is positive down

# Robot physical parameters
physical:
  mass_kg: 15
  displacement_m3: 0.015
  center_of_mass: [0, 0, -0.15]
  center_of_buoyancy: [0, 0,  0.10]

# General control parameters
control:
  dof_num: 5
  dofs:
    surge: true
    sway:  true
    heave: true
    roll:  false
    pitch: true
    yaw:   true
  command:
    wrench:
      max: [69.85, 69.85, 49.39, 0, 5, 7] # 5 & 7 are rough estimates
      scaling: [0.7, 0.5, 1, 0, 1, 1]
    pose:
      rate: [0.20, 0.20, 0.20, 0.35, 0.35, 0.35] # Euler angle pose!

thrusters:
  num: 6
  dof: 5 # Controllable degrees of freedom
  configuration_matrix:
    [[ 0.7071,  0.7071, -0.7071, -0.7071,     0.0,    0.0], # Surge
     [ 0.7071, -0.7071, -0.7071,  0.7071,     0.0,    0.0], # Sway
     [    0.0,     0.0,     0.0,     0.0,     1.0,    1.0], # Heave
     [-0.0467, -0.0467,  0.0467,  0.0467, -0.1600, 0.1600], # Pitch
     [ 0.2143, -0.2143,  0.2143, -0.2143,     0.0,    0.0]] # Yaw

# Controller parameters
controller:
  gains:
    a: 0.1
    b: 3.0
    c: 20.0
  frequency: 1
  setpoint:
    rate:
      linear: 0.20
      angular: 0.35
